DROP TABLE IF EXISTS TBL_EMPLOYEES;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_ARTEXP;

CREATE TABLE TBL_ARTEXP(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(250) NOT NULL,
  exp_string VARCHAR(250) NOT NULL,
  output VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_STOCKS;
CREATE TABLE TBL_STOCKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  stock_quote VARCHAR(250) NOT NULL,
  company_name VARCHAR(250) NOT NULL,
  date TIMESTAMP  NULL,
  price DECIMAL(18,4),
  currency VARCHAR(250) NOT NULL
  
);


